### ISSUE TITLE
add parameter to that would fit to page

### ISSUE THREAD

**Issue by timelyportfolio** [sdwfrost/phylowidget#4]
In [`DiagrammeR`](https://github.com/rich-iannone/Diagrammer), we use a function to fit the rendered svg to its container, so the sizing is controlled by either `sizingPolicy` or the `height` and `width` parameters.  You can see how it would look on `phylowidget` by

```
devtools::install_github("timelyportfolio/phylowidget@feature/sizing")
```

and then running the example from your readme.md.  Then, change to 

```
phylowidget(nwk,height = 200, width = 400)
```

The tiny change can be seen [here](https://github.com/timelyportfolio/phylowidget/compare/feature/sizing).  We could easily add as a parameter in the R code also if you don't want it always on.  Also, I'm planning to work on some pan / zoom available to `DiagrammeR`.  I could easily add that here also if you think it would be helpful.

**Comment by sdwfrost** [comment]
Dear @timelyportfolio , feel free to hack away! The more input, the better; this is part of [this](https://sites.google.com/site/hackout2/), and I'll probably be working on some more widgets today, esp as Ramnath Vaidyanathan is here.

**Comment by sdwfrost** [comment]
I've edited phylowidget.js to include your sizing suggestion - thanks!

**Comment by timelyportfolio** [comment]
how great !  Tell Ramnath hello :)

**Comment by timelyportfolio** [comment]
If you want to see the little bit that I did on phylos, you can go to 

http://bl.ocks.org/timelyportfolio/59acc3853b02e47e0dfc
https://gist.github.com/timelyportfolio/1de4cdd99d92848bc625
