### ISSUE TITLE
support more formats using R conversion

### ISSUE THREAD

**Issue by timelyportfolio** [sdwfrost/phylowidget#5]
It seems Newick is the only format currently supported.  As I'm sure you know, R has a rich set of conversion options.  Even if the Javascript only accepts Newick, I think it would be very valuable to auto-convert some of the common phylo classes.  I could do pull if interested.

**Comment by sdwfrost** [comment]
Hi @timelyportfolio , the JS code takes Newick, and it would be straightforward to tweak the inputs to accept more e.g. phylo, etc. I'm currently working on getting the UI to look nice (may have to use the Bootstrap grid after all), as well as getting a Shiny app to return a Newick string with tagged nodes/branches, so if you want to PR, please go ahead.

**Comment by timelyportfolio** [comment]
Ok, pull submitted.  Any other to-dos I can work on ?

**Comment by timelyportfolio** [comment]
Can see it work with 

```
library(ape)
data(bird.orders)
phylowidget(bird.orders)

### or for a bigger dataset and good test on JS speed
data(bird.families)
phylowidget(bird.families)
```

**Comment by timelyportfolio** [comment]
Will close;  let me know if other formats would be desired

**Comment by sdwfrost** [comment]
Dear @timelyportfolio , thanks for the PRs. As for TODOs, I put some on the [Wiki](https://github.com/sdwfrost/phylowidget/wiki)

**Comment by timelyportfolio** [comment]
should I pull to your repo or the hackerout?

**Comment by sdwfrost** [comment]
please pull to my repo, as I've configured it to be upstream from the
hackout2 repo
